### ISSUE TITLE
Running LSTrAP without a job manager

### ISSUE THREAD

**Issue by icruz1989** [sepro/LSTrAP#2]
Dear authors of LSTrAp,

Thank you for creating this amazing pipeline to carry out transcriptomics analyses. I am writing to you because I am trying to use it and I successfully installed all dependencies. However, the cluster where I am working does not have the configuration engine to carry out the analyses. It is working with SLURM. Thus, I was wondering if there is another way to run the command without using a task manager? running the command just direct into the cluster?

When I run the command I get all the tasks as "done"  but files are empty and I suspect that this is because the cluster problem since I get a notification about the system unsupported.

Thank you very much in advance

Best regards

Ivan

**Comment by sepro** [comment]
Dear Ivan,


SLURM indeed isn't supported (and I don't have access to a cluster running this scheduler so it would be impossible for me to add/test this). You probably could make changes to the config.ini file (parameters that have the qsub_ prefix are relevant here) to correctly submit jobs on your system, I wouldn't recommend it as the tools LSTrAP wraps are fairly out-of-date these days.

If you are construction an expression atlas from publicly available resources have a look at Curse/Prose : http://bioinformatics.psb.ugent.be/webtools/Curse/ (Vaneechoutte et al. ) for a user-friendly option that uses more recent tools. 


Kind regards,
Sebastian
